# Generated by Django 5.2.8 on 2026-03-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='rows',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airplane',
            name='seats_in_row',
            field=models.PositiveIntegerField(default=6),
            preserve_default=False,
        ),
    ]
