# Generated by Django 6.0.1 on 2026-01-13 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
        ('flights', '0002_delete_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airplanes.airplane'),
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
