# Generated by Django 5.2.8 on 2026-02-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('flight', 'seat_number'), name='unique_flight_seat_booking'),
        ),
    ]
