# Generated by Django 5.2.8 on 2026-03-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_ticket_unique_flight_seat_booking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_flight_seat_booking',
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('delayed', 'Delayed'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
    ]
