# Generated by Django 5.2.8 on 2026-03-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_ticket_unique_flight_seat_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired'), ('CONFIRMED', 'Confirmed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
